name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Check and test Rust project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install toolchain
      run: |
        rustup update
        rustup component add clippy
        rustup component add rustfmt
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Check
      run: cargo check --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
