name: Rust CD

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Rust executable
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [aarch64-apple-darwin, x86_64-apple-darwin, aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc]

    steps:
    - uses: actions/checkout@v4
    - name: Build executable
      run: cargo build --verbose --release --target ${{ matrix.target }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}/release
